name: Code Quality Check and Merge

on:
  push:
    branches:
      - taimoor
      - saqib
  pull_request:
    branches:
      - taimoor
      - saqib

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Create Pull Request
      if: success()
      uses: peter-evans/create-pull-request@v3
      with:
        title: 'Code quality check passed'
        commit-message: 'Merge feature branches into main'
        branch: 'main'
        body: |
          Code quality check passed for feature branches:
          - taimoor
          - saqib
