name: Code Quality Check and Merge with Main

on:
  push:
    branches:
      - taimoor
      - saqib

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 --ignore=E501 .

      - name: Test code
        run: |
          pytest tests/

      - name: Merge with main
        if: github.ref == 'refs/heads/taimoor' || github.ref == 'refs/heads/saqib'
        uses: repo-sync/pull-request-action@v2
        with:
          token: ${{ secrets.PAT }}
          allow_modify_same_branch: true
          delete_branch: true
